/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tibo47.weatherPaname.weather.dataprovider.remote.dto


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param description 
 * @param end 
 * @param event 
 * @param senderName 
 * @param start 
 * @param tags 
 */
@Serializable

public data class OneCall200ResponseAlertsInnerDto (

    @SerialName(value = "description")
    val description: kotlin.String? = null,

    @SerialName(value = "end")
    val end: kotlin.Float? = null,

    @SerialName(value = "event")
    val event: kotlin.String? = null,

    @SerialName(value = "sender_name")
    val senderName: kotlin.String? = null,

    @SerialName(value = "start")
    val start: kotlin.Float? = null,

    @SerialName(value = "tags")
    val tags: kotlin.collections.List<kotlin.String>? = null

)

