/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tibo47.weatherPaname.weather.dataprovider.remote.dto


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param day 
 * @param eve 
 * @param morn 
 * @param night 
 */
@Serializable

public data class OneCall200ResponseDailyInnerFeelsLikeDto (

    @SerialName(value = "day")
    val day: kotlin.Float? = null,

    @SerialName(value = "eve")
    val eve: kotlin.Float? = null,

    @SerialName(value = "morn")
    val morn: kotlin.Float? = null,

    @SerialName(value = "night")
    val night: kotlin.Float? = null

)

