/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tibo47.weatherPaname.weather.dataprovider.remote.dto

import com.tibo47.weatherPaname.weather.dataprovider.remote.dto.OneCall200ResponseCurrentWeatherInnerDto
import com.tibo47.weatherPaname.weather.dataprovider.remote.dto.OneCall200ResponseHourlyInnerRainDto

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param clouds 
 * @param dewPoint 
 * @param dt 
 * @param feelsLike 
 * @param humidity 
 * @param pop 
 * @param pressure 
 * @param rain 
 * @param temp 
 * @param uvi 
 * @param visibility 
 * @param weather 
 * @param windDeg 
 * @param windGust 
 * @param windSpeed 
 */
@Serializable

internal data class OneCall200ResponseHourlyInnerDto (

    @Contextual @SerialName(value = "clouds")
    val clouds: java.math.BigDecimal? = null,

    @Contextual @SerialName(value = "dew_point")
    val dewPoint: java.math.BigDecimal? = null,

    @Contextual @SerialName(value = "dt")
    val dt: java.math.BigDecimal? = null,

    @Contextual @SerialName(value = "feels_like")
    val feelsLike: java.math.BigDecimal? = null,

    @Contextual @SerialName(value = "humidity")
    val humidity: java.math.BigDecimal? = null,

    @Contextual @SerialName(value = "pop")
    val pop: java.math.BigDecimal? = null,

    @Contextual @SerialName(value = "pressure")
    val pressure: java.math.BigDecimal? = null,

    @SerialName(value = "rain")
    val rain: OneCall200ResponseHourlyInnerRainDto? = null,

    @Contextual @SerialName(value = "temp")
    val temp: java.math.BigDecimal? = null,

    @Contextual @SerialName(value = "uvi")
    val uvi: java.math.BigDecimal? = null,

    @Contextual @SerialName(value = "visibility")
    val visibility: java.math.BigDecimal? = null,

    @SerialName(value = "weather")
    val weather: kotlin.collections.List<OneCall200ResponseCurrentWeatherInnerDto>? = null,

    @Contextual @SerialName(value = "wind_deg")
    val windDeg: java.math.BigDecimal? = null,

    @Contextual @SerialName(value = "wind_gust")
    val windGust: java.math.BigDecimal? = null,

    @Contextual @SerialName(value = "wind_speed")
    val windSpeed: java.math.BigDecimal? = null

)

