/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tibo47.weatherPaname.weather.dataprovider.remote.dto

import com.tibo47.weatherPaname.weather.dataprovider.remote.dto.OneCall200ResponseAlertsInnerDto
import com.tibo47.weatherPaname.weather.dataprovider.remote.dto.OneCall200ResponseCurrentDto
import com.tibo47.weatherPaname.weather.dataprovider.remote.dto.OneCall200ResponseDailyInnerDto
import com.tibo47.weatherPaname.weather.dataprovider.remote.dto.OneCall200ResponseHourlyInnerDto
import com.tibo47.weatherPaname.weather.dataprovider.remote.dto.OneCall200ResponseMinutelyInnerDto

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param alerts 
 * @param current 
 * @param daily 
 * @param hourly 
 * @param lat 
 * @param lon 
 * @param minutely 
 * @param timezone 
 * @param timezoneOffset 
 */
@Serializable

internal data class OneCall200ResponseDto (

    @SerialName(value = "alerts")
    val alerts: kotlin.collections.List<OneCall200ResponseAlertsInnerDto>? = null,

    @SerialName(value = "current")
    val current: OneCall200ResponseCurrentDto? = null,

    @SerialName(value = "daily")
    val daily: kotlin.collections.List<OneCall200ResponseDailyInnerDto>? = null,

    @SerialName(value = "hourly")
    val hourly: kotlin.collections.List<OneCall200ResponseHourlyInnerDto>? = null,

    @Contextual @SerialName(value = "lat")
    val lat: java.math.BigDecimal? = null,

    @Contextual @SerialName(value = "lon")
    val lon: java.math.BigDecimal? = null,

    @SerialName(value = "minutely")
    val minutely: kotlin.collections.List<OneCall200ResponseMinutelyInnerDto>? = null,

    @SerialName(value = "timezone")
    val timezone: kotlin.String? = null,

    @Contextual @SerialName(value = "timezone_offset")
    val timezoneOffset: java.math.BigDecimal? = null

)

