/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tibo47.weatherPaname.weather.dataprovider.remote.dto


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param day 
 * @param eve 
 * @param max 
 * @param min 
 * @param morn 
 * @param night 
 */
@Serializable

public data class OneCall200ResponseDailyInnerTempDto (

    @Contextual @SerialName(value = "day")
    val day: java.math.BigDecimal? = null,

    @Contextual @SerialName(value = "eve")
    val eve: java.math.BigDecimal? = null,

    @Contextual @SerialName(value = "max")
    val max: java.math.BigDecimal? = null,

    @Contextual @SerialName(value = "min")
    val min: java.math.BigDecimal? = null,

    @Contextual @SerialName(value = "morn")
    val morn: java.math.BigDecimal? = null,

    @Contextual @SerialName(value = "night")
    val night: java.math.BigDecimal? = null

)

