[versions]
agp = "8.3.2"
kotlin = "1.9.20"
ksp = "1.9.20-1.0.14"
hilt = "2.48.1"
kotlinter = "4.1.1"
kover = "0.7.5"
openapiGenerator = "7.2.0"

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jetbrainsKotlinPluginSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
devtoolsKsp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
daggerHiltAndroid = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
jmailenKotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }
jetbrainsKotlinxKover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
openapiGenerator = {id = "org.openapi.generator", version.ref = "openapiGenerator" }
